"""
Script to convert a standard RLDS dataset to LeRobot format using tfds.load.

This script is suitable for datasets with metadata correctly generated by the `tensorflow_datasets` tool.

Usage:
python your_script_name.py --dataset-name "panda_rlds_dataset" --data-dir "/path/to/your/parent/directory"

You can also push the final dataset to the Hugging Face Hub:
python convert_my_data.py --dataset-name "panda_rlds_dataset" --data-dir "/path/to/your/data" --push-to-hub

Note: Please make sure the following packages are installed before running this script:
`pip install lerobot tensorflow tensorflow-datasets tyro`
"""
import shutil
import os
import tyro
import tensorflow as tf
import tensorflow_datasets as tfds
from lerobot.common.datasets.lerobot_dataset import LeRobotDataset, HF_LEROBOT_HOME



def main(repo_id: str, dataset_name: str, data_dir: str, *, push_to_hub: bool = False):
    """
    Main conversion function.

    Args:
        dataset_name: Name of the TFDS dataset to load (e.g. "panda_rlds_dataset").
        data_dir: Parent directory containing the TFDS dataset folder.
        push_to_hub: If True, push the converted dataset to Hugging Face Hub.
    """

    output_path = HF_LEROBOT_HOME / repo_id # HF_LEROBOT_HOME is defined for LeRobotDataset
    if output_path.exists():
        print(f"Removing existing dataset: {output_path}")
        shutil.rmtree(output_path)


    print("Creating LeRobot dataset structure...")
    dataset = LeRobotDataset.create(
        repo_id=repo_id,
        robot_type="franka_panda",
        fps=5,  # TODO bingwen
        features={
            "image": {
                "dtype": "image",
                "shape": (480, 480, 3),
                "names": ["height", "width", "channel"],
            },
            "wrist_image": {
                "dtype": "image",
                "shape": (480, 480, 3),
                "names": ["height", "width", "channel"],
            },
            "state": {
                "dtype": "float32",
                "shape": (8,),
                "names": ["state"],
            },
            "actions": {
                "dtype": "float32",
                "shape": (7,),
                "names": ["actions"],
            },
        },
        image_writer_threads=10,
        image_writer_processes=5,
    )


    # --- 3. Load the original dataset using tfds.load ---
    print(f"Loading TFDS dataset '{dataset_name}' from directory '{data_dir}'")
    try:
        raw_dataset, ds_info = tfds.load(name=dataset_name, data_dir=data_dir, split="train", with_info=True)
        print("\n=== Dataset Info ===")
        print(ds_info)
    except Exception as e:
        print(f"Error: Failed to load dataset using tfds.load. Please check if `dataset_name` and `data_dir` are correct.")
        print(f"TensorFlow error message: {e}")
        return


    # --- 4. Iterate over data and write to LeRobot dataset ---
    print("Starting conversion process...")
    for episode in raw_dataset:
        # In RLDS format, each episode contains a 'steps' dataset
        # We need to iterate over these steps to build a LeRobot episode
        num_steps = 0
        language_instruction = None
        for step in episode["steps"].as_numpy_iterator():
            if language_instruction is None:
                language_instruction = step["language_instruction"].decode('utf-8')
            dataset.add_frame(
                {
                    "image": step["observation"]["image"],
                    "wrist_image": step["observation"]["wrist_image"],
                    "state": step["observation"]["state"],
                    "actions": step["action"],
                    "task": language_instruction, # designed for multitask in one episode
                }
            )
            num_steps += 1

        if num_steps > 0: # only save if the episode is valid
            dataset.save_episode()
            print(f"Saved episode for task '{language_instruction}' (containing {num_steps} steps)")
        else:
            print("Found an empty episode, skipped.")


    if push_to_hub:
        print("Pushing to Hugging Face Hub...")
        dataset.push_to_hub(
            tags=["panda", "rlds", "robotics"], 
            private=True,
            push_videos=True,
            license="apache-2.0",
        )

    print("\nConversion complete!")
    print(f"LeRobot dataset saved to: {output_path}")

if __name__ == "__main__":
    tyro.cli(main)